Default: &defaults
  database: yesod-blog.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-blog_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-blog_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-blog_production.sqlite3
  poolsize: 100
  <<: *defaults
